language: node_js
node_js:
    - 12
services: mongodb
before_install: cd backend

deploy:
    provider: heroku
    api_key:
      secure: "3f9ecd04-59e8-4608-bf2e-81d5a94773dc"
    app: adhoccer
    on: main