language: node_js
node_js:
- 12
services: mongodb
before_install:
- openssl aes-256-cbc -K $encrypted_c121153bf40d_key -iv $encrypted_c121153bf40d_iv
  -in adhoccer-6c80dfc646e9.json.enc -out backend/adhoccer-6c80dfc646e9.json -d
- cd backend
deploy:
  provider: gae
  keyfile: adhoccer-6c80dfc646e9.json
  project: adhoccer
  on: main