language: node_js
node_js:
- 12
services: mongodb
before_install: cd backend
deploy:
  provider: heroku
  api_key:
    secure: aaf+yusS4m/JhE1vz3JjZbXYQgT6Uv33Wkv6Z4QZ53jnYmJWrxYFIR0fsd37r24ezZ3iDk08U8kCniAMm4kYwELAUF2P0kQvHK1RBfgmjx7ou9ZcWE2VxbBVs1zHkCd8ruUf4Wd7CmB5B1uphpxpKn/GjEyQ5Bfy9oWN1eOl+kDk1meAGnYqB9VbRwRJPivKLmYEfQ3dOWpY4S8+HMR7IgYVvU/3hUsvUCQ11PQ/VfOXnIteIu9Q/dHmOD0fBgfLKiSUJFVgPYrY/zuL2H8JRcjB3ryUZc/6lHYtx7kShjTOjsKDJQCcVYhI3uFHgpat/s6zjXLJ5JxeS9gQk7qBIcqGIa4MzdyDdjMvQUQkT8LrnbfaSOya02DNbeAhntjqWdagpwUoXCKsn66JZKfem/LFPyzvng4VaPCUbUedxBTXLr+7tnNN++3Lxx5zWqLUnfSzDJfnvvWhRIKxxCgqMYU1oSRbR5iqRokAmw+xBnXmDTTsnL3p4dtxO9KpV5ozJ02Xnje6xttTIaxzjVKhXskDVi81Hs24bRW65jPdpeodl2oadvES30BWE+O4Z3xqhfS/TsN79Dg3SvVHQgeQt9Q2/UJjpnvzSfAXSFek/wOuPb8+BOmIZm6+pUR+UfFNsVGQOYMhGjWN1T6ebBygKZBaNyUCWct9n23eSDeLeu8=
  app: adhoccer
  on: main
