version: '3.8'

services:
  backend:
    image: adhoccer-backend
    build: 
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
        - "27017:27017"

  frontend:
    image: adhoccer-frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app/
      - /app/frontend/node_modules
    stdin_open: true
    restart: on-failure